---
title: Vlinderbloemigen op XVIII Silage Conference
author: ~
date: '2018-10-11'
slug: nav-xviii-silage-conference-vlinderbloemigen
bibliography: library.bib
banner: img/XVIII_conf.png
categories: []
tags: []
---

In juli 2018 werd in Bonn een wetenschappelijke conferentie over silages gehouden. Helaas was ik niet aanwezig, maar omdat het onderwerp bijzonder relevant voor ons is heb ik de bijdrages doorgelezen. Samenvattingen van alle bijdrages vindt u via deze link [https://www.isc2018.de/Download/Proceedings](https://www.isc2018.de/Download/Proceedings). In deze post ga ik in op een aantal onderzoeken op het gebied van vlinderbloemige gewassen. In latere posts ga ik in op andere onderwerpen tijdens.

### Can luzerne replace grass silage in Nordic climate

@sairanen2018 onderzochten inzet van luzerne in finse grasrantsoenen. Hiervoor zaaiden ze een mengsel van luzernerassen en gebruikten de tweede snede graskuil en luzernekuil voor het onderzoek. Resultaten met een rantsoen met graskuil 55% graskuil en 45% krachtvoer op DS basis werden vergeleken met resultaten van een rantsoen met 54% ruwvoer (40% luzerne en 60% graskuil) aangevuld met krachtvoer. 

De drogestofopname steeg door inzet van luzerne van gemiddeld 19.9 kg DS/koe/dag naar 23.1 kg DS/koe/dag. Ook steeg de productie van 29.3 kg kg/koe/dag naar 31.3 kg/koe/dag. Ondanks de hogere productie was de voerefficiëntie in het luzernerantsoen lager, en werd het eiwit minder goed benut.

De onderzoekers zagen dat productie van grasland veel hoger was dan van het land ingezaaid met luzerne. Toch waren ze positief omdat inzet van luzerne in een grasrantsoen leidde tot hogere opname en productie. Deze resultaten komen overeen met resultaten uit andere onderzoeken, zoals bijvoorbeeld genoemd in @Dewhurst2009.

### Conservering en inzet van soja GPS

@tabacco2018 onderzochten de conservering van GPS van twee sojarassen. De planten van twee sojarassen werden met twee maturatiestadia ingekuild (R4-5, volledige ontwikkeling van de boon, R7 vroegrijp), en daarnaast werden het gewas zonder en met melkzuurvormend inkuilmiddel ingekuild.

De opbrengst varieëerde tussen de 4.9 en 5.6 ton DS/ha, waarbij vooral de opbrengst van het tweede ras fors toenam in R7. Ruweiwitgehalte varieërde tussen de 16.7% en 25%. In stadium R4-R5 was er zonder inkuilmiddel sprake van boterzuurfermentatie, terwijl de kuilen van R7 zonder en met inkuilmiddel goed geslaagd waren. 

De onderzoekers concludeerden dat inkuilen van soja GPS een goed en eenvoudig alternatief kan voor de oogst van soja. Deze resultaten zijn interessant omdat de teelt van soja ook in Nederland aandacht krijgt, en omdat er recent een proef is uitgevoerd met oogst van soja GPS in Nederland, zie [https://bit.ly/2NFq2Wk](https://bit.ly/2NFq2Wk). In dit geval werd de soja achter bloembollen geteeld en bracht in de zeer droge zomer van 2018 ca 6 ton DS/ha op. Interessant om toe noemen is dat soja tot de jaren '50 werd geteeld als ruwvoergewas (zie https://www.feedipedia.org/node/294).

Het onderzoek van @tabacco2018 werd vervolgd met een voerproef, waarin GPS silage van soja sojaschroot verving (@comino2018). Het aandeel ruwvoer in het rantsoen nam hierdoor toe van 65.1% naar 70.5%. Productie daalde van 29.5 kg/koe/dag naar 28.5 kg/koe/dag maar vet en eiwitopbrengsten waren gelijk. 

### Influence of ensiling and thermal treatment of peas on their feed value

@kuhnitzsch2018 onderzochten de invloed van inkuilen en verhitting op de voedingswaarde van erwten. Hiervoor werden ingekuild met melkzuurbacteriën, en vervolgens verhit tot 120 oC gedurende 30 minuten.

Vergeleken met onbehandelde bonen nam de oplosbaarheid van eiwit door inkuilen af van 71.5% naar 66%. De oplosbaarheid nam verder af tot 59% door verhitting. Oplosbaarheid van het eiwit nam daarintegen toe door enkel verhitting. 

Het onderzoek is interessant omdat inkuilen een praktische manier is om erwten die niet volledig droog zijn te bewaren. Daarnaast is het relevant omdat melkveerantsoenen over het algemeen voldoende onbestendig eiwit en een terkort aan onbestendig eiwit bevatten. Combinatie van inkuilen en toasten is dan een interessante optie.

### Effect of silage additives on the fermentation and the protein quality of clovergrass mixture

@gallo2018 vergeleken inzet van een inkuilmiddel gebaseerd op *Lactobacillus Plantarum* met een chemisch middel gebaseerd op natrium nitriet en natrium hexamine op de conservering en eiwitkwaliteit van gras-klaverkuilen.

Vergeleken met de controlebehandeling (geen toevoegmiddel) was het NH3 gehalte van de kuil met het chemische middel het laagst, gevolgd door *L Plantarum*. Ook boterzuur was het laagst met het chemische middel. De onzoekers concludeerden dat een middel gebaseerd op *L. Plantarum* leidde tot verbetering van het inkuilproces maar dat dit niet voldoende was om boterzuurfermentatie, en daarmee eiwitverliezen echt te verminderen, en raadden daarom inzet van het chemische middel in dit soort situaties aan.

Deze resultaten zijn bijzonder interessant in de context van moeilijk in te kuilen gewassen, waarin veel eiwitverliezen optreden. Ze moeten ook in verband worden gezien met het resultaat van @martens2018 en met die van @pieper2009, waarin zeer duidelijk wordt aangetoond dat de combinatie van beide middelen tot de beste resultaten leidt.

### Protein degradation during ensiling comparing tannin extracts to conventional additives exemplified by lucerne (Medicago Sativa)

Het is bekend dat tannines eiwit kunnen binden waardoor dit bestendiger wordt. Dit is de basis achter de reden waarom inzet van gewassen als Sainfoin of Boekweit leidt tot een hoger aandeel bestendig eiwit in rantsoenen (@Copani2015, @Leiber2012, @Amelchanka2010). @martens2018 vergeleken inzet van tannines met verschillende inkuilmiddelen op de eiwitfracties van een groot aantal luzernekuilen tussen 2013 en 2016. Dit onderzoek is een vervolg op het onderzoek van @pieper2009.

Uit de resultaten van @martens2018 blijkt dat de combinatie van mierenzuur en een middel baseerd op *L. Plantarum* leidt tot een lagere A-fractie van het eiwit (oplosbaar eiwit, oa ammoniak) in de onderzochte kuilen. Dezelfde verlaging van de A-fractie kan worden bereikt door inzet van 3% tannines op productbasis. Dit is onpraktisch veel, en zal ongetwijfeld te duur zijn voor praktische toepassing. 
 
### Effects of additive, herbage dry matter concentration and clostridia inoculation on fermentation quality of a red clover-grass silage

@konig2018 ondezochten het inkuilproces van rode klaver-gras silage. Hiervoor werd rode klaver-gras met twee DS gehaltes ingekuild (20% en 31%). De helft van de kuilen werden geinoculeerd met boterzuurbacteriën, en verschillende inkuilmiddelen werden per DS-gehalte toegepast (geen inkuilmiddel, 4 liter mierenzuur/ton, 900 natrium nitriet/ton). 

Inoculatie met boterzuurbacteriën veranderde niet veel aan het inkuilproces omdat het aantal boterzuursporen al hoog was in het oorspronkelijke product. Toevoegmiddelen leidden tot lagere NH3 gehaltes. Het nitraatgehalte was in de onbehandelde kuilen al hoog genoeg om groei van *Clostridia* te remmen (minimum 4.3 gram NO3/kg DS volgens resultaten van @Kaiser1997).

### Improving nitrogen utilization of alfalfa protein by co-ensiling wit red clover

Het is bekend dat het enzym polyphenol oxidase (PPO), dat in hoge concentraties voorkomt in rode klaver, proteolyse remt. @dong2018 maakten experimentele silages van enkel luzerne, luzerne:rode klaver verhouding 1:1 en rode klaver en onderzochten de eiwitkwaliteit in deze silages.

Door luzerne samen met rode klaver in te kuilen nam proteolyse in luzerne af. @dong2018 zagen dit omdat NH3 als aandeel van het totale N hoger was in de silages van luzerne dan in de silages met rode klaver. Ook was het aandeel vrije aminozuren en peptides in de luzernesilages hoger dan in de silages met rode klaver. Ze concludeerden hieruit dat proteolyse in luzernekuilen verminderd kan worden door inzet een deel rode klaver.

## Referenties
