---
title: "Rode klaver in rantsoenen"
author: "Albart Coster"
date: '2018-08-16'
output: pdf_document
bibliography: library.bib
categories: []
slug: rode-klaver-in-rantsoenen
tags:
- rode klaver
- rantsoen
- proteolyse
banner: img/rode_klaver.jpg
---

Het onderzoeksproject [Legumeplus](legumeplus.eu) is een groot
europees onderzoek naar teelt en inzet van vlinderbloemige
ruwvoergewassen. 

Zoals andere vlinderbloemigen bindt rode klaver in samenwerking met
bacteriën stikstof uit de lucht voor eigen groei. Hierdoor heeft het
gewas veel minder of geen stikstofbemesting nodig dan een
vergelijkbaar gewas dat deze eigenschappen niet heeft (zie
bijvoorbeeld fotos 1 en 4 en tabelen 1 en 2 uit @DeWit2015. Vergeleken met
engels raaigras wortelt rode klaver dieper, waardoor het beter bestand
is tegen droogte (zie figuur 3 in @DeWit2015). Vergeleken met luzerne
is rode klaver minder gevoelig voor iets zuurdere grond, maar het
groeit het beste bij een pH hoger dan 6. Ook is het minder
droogteresistent dan luzerne, maar kan het weer beter tegen natte
grond (net als rolklaver dat weer beter tegen droogte kan dan rode
klaver,
[https://extension.psu.edu/red-clover](https://extension.psu.edu/red-clover)).

Naast deze interessante agronomische eigenschappen bevat rode klaver
relatief hoge gehaltes van het enzym *polyphenol
oxidase* (PPO). PPO in rode klaver is aanwezig in een actieve en
grotendeel in een inactieve vorm (@Lee2014). Activatie van PPO
gebeurt door beschading van de cel. Actieve PPO zet bepaalde plant
phenolen om in andere phenolen, die ook in hoge mate aanwezig zijn in
rode klaver (@Lee2014), in aanwezigheid van zuurstof. Deze
reactieproducten vormen complexen met verschillende moleculen, waaronder
vetzuren en eiwitten. Door deze complexvorming wordt
eiwitafbraak in de pens maar ook al tijdens de aerobe fase van het inkuilproces verminderd
(@Copani2014). Ook wordt hydrogenatie van onverzadigde vetzuren
verminderderd zodat dierlijke producten meer Omega 3 vetzuren
(@Halmemies-Beauchet-Filleau2014, @Dewhurst2009). Interessant genoeg
wordt deze omzetting van phenolen door PPO geblokkeerd door toevoeging
van sorbinezuur (een antioxidant) (@Lee2009), zodat wij inzet van
kaliumsorbaat wellicht nog eens moeten heroverwegen.

In een uitgebreide samenvatting noemen @Dewhurst2009 dat inzet van
vlinderbloemigen over het algemeen leidt tot hogere opname, en dit
leidt weer tot hogere productie. Vergeken met engel raaigras heeft
rode klaver een lagere verteerbaarheid en bevat het meer eiwit, maar neemt de verteerbaarheid
veel minder af met maturatiestadium (Tabel 7 uit
@Dewhurst2009). @Dewhurst2009 relateren de hogere opname door inzet van
vlinderbloemigen aan hun chemische structuur. Vergeleken met raaigras
breekt het makkelijker, waardoor een deel van de klaver sneller
fermenteert in de pens, en ook weer sneller doorstroomt (dit geldt
bijvoorbeeld ook voor luzerne). 

Hogere opname door inzet van rode klaver vergeleken met enkel gras werd ook gevonden door
@Halmemies-Beauchet-Filleau2014, maar opname daalde als het ruwvoer
enkel uit rode klaver bestond. In grasrantsoenen stijgt de opname
overigens ook door inzet van luzerne (@sairanen2018). @Broderick1995 zagen dat opname van
rode klaver lager was dan van luzerne, in rantsoenen waar het ruwvoer
enkel uit luzerne of rode klaver bestond. Omdat voerefficiëntie vrijwel
gelijk bleef en conditie toenam, en deze auteurs concludeerden dat
rode klaverkuil ongeveer 10% meer energie bevatte dan luzernekuil. Ook
@Broderick2001 zagen dat opname daalde als luzerne werd vervangen,
zowel in een rantsoen met enkel luzerne of rode klaver als in een
rantsoen met een aandeel snijmais. Ook hier vonden de onderzoekers dat
conditie van de koeien die rode klaver aten toenam vergeleken met de
luzernerantsoenen. In dit geval was de productie in de rantsoenen met
rode klaver zelfs hoger, ondanks de lagere opname.

Inzet van rode klaver leidt tot hogere aandelen onverzadigd vet in de
melk (@Halmemies-Beauchet-Filleau2014). In sommige gevallen daalde het
melkvetgehalte door inzet van rode klaver (@Broderick1995), maar in
andere gevallen steeg het
(@Broderick2001). @Halmemies-Beauchet-Filleau2014 zagen dat vetgehalte
het hoogst was als rode klaver samen met andere grassilage werd
gevoerd (net als opname en productie).

Inzet van rode klaver leidt tot lagere ureumgehaltes in de melk omdat
rode klaver minder oplosbaar eiwit en ammoniak bevat dan gras- en
luzernekuilen van vergelijkbare kwaliteit (@Broderick1995,
@Broderick2001, @Copani2014). Daarnaast leidt inzet van rode klaver
tot hogere bestendigheid van aminozuren in de pens, maar niet elk
aminozuur is even bestendig (@Halmemies-Beauchet-Filleau2014). Invloed op melkeiwitgehalte is
wisselend. @Broderick1995 zagen dat inzet van rode klaver het
eiwitgehalte licht verlaagde (koeien aten ook minder), @Broderick2001
zagen ook een lichte afname van het
melkeiwitgehalte. @Halmemies-Beauchet-Filleau2014 zagen dat de
rantsoenen met rode klaver en gras leiden tot de hoogste eiwitgehaltes
en eiwitproducties.

## Conclusie

Rode klaver is een interessant alternatief voor luzerne omdat het
makkelijker te telen lijkt in combinatie met luzerne, en minder eisen
stelt aan de bodem. Vergeleken met luzerne heeft het ook als voordeel
dat het minder oplosbaar eiwit bevat, waardoor ureumgehaltes in de
melk minder zullen stijgen. Rode klaver lijkt vooral goed te werken in
combinatie met graskuil, wellicht door fysieke structuur en doordat
het minder onbestendig eiwit bevat. Voor maxamale opname van graskuil
kan inzet van rode klaver dus verstandig zijn. In rantsoenen met veel snijmais
moet het aandeel onbestendig eiwit wellicht goed in de gaten worden
gehouden. 

## Bronnen

